base_dir: logs
data:
  batch_size: 64
  data_name: pems04
  data_filename: datasets/PEMS08/pems08.npz
  cache_dir: None
  metrics: [rmse, mae]

model:
  name: TransformerRegression
  N: 3
  n_heads: 4
  hidden_dim: 128
  ffn_dim: 512
  input_process_dim: 32
  output_process_dim: 32
#  T: 288
#  h: 12
#  D: 170

train:
  dropout_rate: 0.1
  lr: 0.001
  epoch: 0
  max_epoch: 500
  lr_scheduler: PlateauLRScheduler
  patience: 10