base_dir: logs
data:
  batch_size: 64
  data_name: pems04
  data_filename: datasets/PEMS04/pems04.npz
  T_skip: 288
  cache_dir: None
  metrics: [rmse, mae]

model:
  name: Transformer
  N: 6
  n_heads: 8
  hidden_dim: 512
  ffn_dim: 2048
  input_process_dim: 32
  output_process_dim: 32


train:
  dropout_rate: 0.1
  lr: 0.001
  epoch: 0
  max_epoch: 500
  lr_scheduler: PlateauLRScheduler
  patience: 15